version: '3.3'
services:
  web:
    build:
      context: ./www
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes: 
      - ./www:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webjump
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
